### ISSUE TITLE
Getting Resource 'random_shuffle.random' not found Exception

### ISSUE THREAD

**Issue by selvanponraj** [kwilczynski/terraform-templates#6]
terraform plan error

module.subnet-calculator.output.random: Resource 'random_shuffle.random' not found for variable 'random_shuffle.random.result'

terraform init 

* provider.aws: version = "~> 1.26"
* provider.null: version = "~> 1.0"
* provider.random: version = "~> 1.3"

**Comment by kwilczynski** [comment]
Hi @selvanponraj, sorry that you are having issues.

What version of Terraform do you run? Perhaps there is some difference.

**Comment by selvanponraj** [comment]
Hi, Thanks for the quick response. I am using Terraform v0.11.7

**Comment by kwilczynski** [comment]
Hi @selvanponraj, thank you!

I will try to reproduce your issues and report back.

Going forward, my module is not going to be needed, as the following might be included in the Terraform itself: https://github.com/hashicorp/terraform/pull/15106.

By the way, do you happen to have a small template you could share which would showcase the issue?

**Comment by selvanponraj** [comment]
Invited you to be a part of the group. Please accept.

```hcl
module "subnet-calculator" {
  source = "./modules/common/subnet-calculator"
  cidr_block = "172.16.0.0/16"
  to = "/20"
}
```

Any help on this would be great.

**Comment by kwilczynski** [comment]
Hi @selvanponraj,

I have pushed a fix, which makes the `subnet-calculator` module compatible with changes introduced in Terraform 0.11.x, etc. It should work now.

An example using your sample network range:

```hcl
module "test" {
  source     = "./subnet-calculator"
  cidr_block = "172.16.0.0/16"
  to         = "/20"
  shuffle    = true
}

output "cidr_block" {
  value = "${module.test.cidr_block}"
}

output "address" {
  value = "${module.test.address}"
}

output "netmask" {
  value = "${module.test.netmask}"
}

output "hosts" {
  value = "${module.test.hosts}"
}

output "subnets" {
  value = "${module.test.subnets}"
}

output "random" {
  value = "${module.test.random}"
}

output "all" {
  value = "${module.test.all}"
}
```

Should yield something akin to this:

```shell
$ terraform output
address = 172.16.0.0
all = [
    172.16.0.0/20,
    172.16.16.0/20,
    172.16.32.0/20,
    172.16.48.0/20,
    172.16.64.0/20,
    172.16.80.0/20,
    172.16.96.0/20,
    172.16.112.0/20,
    172.16.128.0/20,
    172.16.144.0/20,
    172.16.160.0/20,
    172.16.176.0/20,
    172.16.192.0/20,
    172.16.208.0/20,
    172.16.224.0/20,
    172.16.240.0/20
]
cidr_block = 172.16.0.0/16
hosts = 4094
netmask = 255.255.0.0
random = [
    [
        172.16.192.0/20,
        172.16.16.0/20,
        172.16.144.0/20,
        172.16.32.0/20,
        172.16.64.0/20,
        172.16.48.0/20,
        172.16.160.0/20,
        172.16.208.0/20,
        172.16.112.0/20,
        172.16.80.0/20,
        172.16.240.0/20,
        172.16.176.0/20,
        172.16.128.0/20,
        172.16.96.0/20,
        172.16.0.0/20,
        172.16.224.0/20
    ]
]
subnets = 16
```

Please, let me know if the fix works for you.

**Comment by kwilczynski** [comment]
Hi @selvanponraj, I am going to close this issue for now. Feel free to re-open if needed.

**Comment by selvanponraj** [comment]
Sorry for the delayed reply and PC was not accessible during the weekend. I have tested this morning and it is working fine.

Many thanks for your kind help and support.
